### ISSUE TITLE
HTML rendered as Image is cut in PDF when exporting a survey on Nuxt.js

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-pdf#271]
A problematic sample available in the following user issue: T14587 - CompletedHTML text as a part of survey PDF
https://surveyjs.answerdesk.io/internal/ticket/details/T14587

**Comment by JaneSjs** [comment]
HTML added in code (the “Specialists advise…” footer) was clipped in the exported PDF. That comes from Vuetify’s global reset:
```css
* {
  padding: 0;
  margin: 0;
}
```

SurveyJS PDF measures HTML in the page before drawing it. With that reset, headings and lists are measured smaller than they render, so the HTML question box is too short and the content is cut off.
To solve the issue, override the reset on the PDF HTML container:

```css
.__surveypdf_html * {
  padding: revert;
  margin: revert;
}
```
